### ISSUE TITLE
Help needed cursor_put and MDB_MULTIPLE

### ISSUE THREAD

**Issue by matija-kovacek-1995** [bendiken/lmdbxx#29]
Hi, I am trying yo use lmdb++ to work with LMDB. I have it working via the example you provided. I have a problem when trying to use cursor_put with MDB_MULTIPLE. I cant seem to get it to work right. Here is the code: 

`std::vector<int> rawData(1000000, std::rand());
MDB_val value1, value2, key;
value1.mv_size = sizeof(int);
value1.mv_data = const_cast<void*> (static_cast<const void*> (&rawData[0]));;
value2.mv_size = 1000000;
MDB_val mData[2] = { value1, value2 };
int i = 0;

auto env = lmdb::env::create();
env.set_mapsize(1UL * 1024UL * 1024UL * 1024UL); /* 1 GiB */
env.open(path.c_str(), 0, 0664);
auto wtxn = lmdb::txn::begin(env);
auto dbi = lmdb::dbi::open(wtxn, nullptr, MDB_DUPSORT | MDB_DUPFIXED | MDB_INTEGERDUP | MDB_CREATE);
auto cursor = lmdb::cursor::open(wtxn, dbi);
key.mv_size = sizeof(i);
key.mv_data = &i;
cursor_put(cursor, &key, mData, MDB_MULTIPLE);`

I think  I am probably misusing the lib or some part of it. So any advice would be good.

**Comment by hoytech** [comment]
Hi! In what way isn't it working right? Do you have a complete test-case we can try?

**Comment by matija-kovacek-1995** [comment]
The code I wrote above is the one I tired. Could be that I am doing something wrong. The data file on the hard disk  does not grow bigger. If I use database handle to write into database 1000000 records the file size is about 20 MB, while if I use cursor_put with  1000000 records and flag MDB_MULTIPLE I get an data file of 12KB, and it is empty when I try and read it. I use the three functions below to test it. Before calling each function I close the application. 
I guess the repro steps would be: 
1. Create database One at first directory.
2. Write 1000000 ints into it using  databasehandle.put. 
3. Observe the database size.
4. Read the data from the database.
5. Create database Two at second directory.
6. Write 1000000 ints into it using cursor_put and MDB_MULTIPLE
7. Notice that database size is different 
8. On reading data base it appears to be empty.

I will also attach the functions I use to do this below again it could be just miss usage due to me not understanding something. 
[LMDB_TESTS.txt](https://github.com/drycpp/lmdbxx/files/6074610/LMDB_TESTS.txt)

**Comment by hoytech** [comment]
* You don't call `wtxn.commit()` in `cursorPut()` so nothing is actually committed
* Once you fix that, I don't think this line is doing what you think:
   `std::vector rawData(1000000, std::rand());`
  All the elements in the array will contain the same value, so you are setting the same key/value over and over again. Try putting this line after that to ensure they are all different values:
  `for (size_t i = 0; i < rawData.size(); i++) rawData[i] = (int)i;`
* Not related, but `*index` after this will likely result in unaligned memory access:
  `const mdb_size_t* index = reinterpret_cast<mdb_size_t*>(key.data());`
  ... which may or may not matter depending on your processor. An easier approach is described in my C++17 fork of lmdbxx which I suggest you check out since this one isn't maintained: https://github.com/hoytech/lmdbxx/

**Comment by matija-kovacek-1995** [comment]
Hi, thank  you for your time. It works now and I will use the C++ 17 fork  going forward.  
Again, I am sorry I had to bother you with it next time I will be more careful what I am doing.

**Comment by hoytech** [comment]
Don't worry about it, I'm glad you got it working.
